# Generated by Django 4.1.5 on 2023-01-26 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('category', models.CharField(choices=[('FILM', 'Film'), ('PARTY', 'Party')], default='FILM', max_length=10)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theatre.film')),
                ('hall_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theatre.hall')),
            ],
        ),
    ]
