# Generated by Django 4.1.5 on 2023-02-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theatre', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theatre.event')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theatre.seat')),
            ],
        ),
    ]
